
import React from 'react';
import { Crop, UserRole, VehicleType } from './types';

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
];

// Standard vehicles configuration
export const TRANS_VEHICLES: VehicleType[] = [
  {
    id: 'bike_1',
    name: 'Bike Delivery',
    icon: 'fas fa-motorcycle',
    capacity: 15,
    basePrice: 30,
    perKmPrice: 6,
    perKgPrice: 0.5,
    minPrice: 30,
    popular: false,
  },
  {
    id: 'auto_1',
    name: 'Auto Rickshaw',
    icon: 'fas fa-cube',
    capacity: 50,
    basePrice: 50,
    perKmPrice: 8,
    perKgPrice: 1,
    minPrice: 50,
    popular: true,
  },
  {
    id: 'pickup_1',
    name: 'Pickup Truck',
    icon: 'fas fa-truck-pickup',
    capacity: 500,
    basePrice: 150,
    perKmPrice: 15,
    perKgPrice: 2,
    minPrice: 150,
    popular: false,
  },
  {
    id: 'truck_1',
    name: '4-Wheeler Truck',
    icon: 'fas fa-truck',
    capacity: 1000,
    basePrice: 250,
    perKmPrice: 20,
    perKgPrice: 2.5,
    minPrice: 250,
    popular: false,
  },
  {
    id: 'tempo_1',
    name: 'Tempo',
    icon: 'fas fa-van-shuttle',
    capacity: 300,
    basePrice: 120,
    perKmPrice: 12,
    perKgPrice: 1.5,
    minPrice: 120,
    popular: false,
  },
];

export const CROPS: Crop[] = [
  { id: '1', name: 'Tomato', category: 'Vegetable', icon: '🍅' },
  { id: '2', name: 'Wheat', category: 'Grain', icon: '🌾' },
  { id: '3', name: 'Onion', category: 'Vegetable', icon: '🧅' },
  { id: '4', name: 'Rice', category: 'Grain', icon: '🍚' },
  { id: '27', name: 'Basmati Rice', category: 'Grain', icon: '🍚' },
  { id: '5', name: 'Cotton', category: 'Commercial', icon: '☁️' },
  { id: '6', name: 'Mango', category: 'Fruit', icon: '🥭' },
  { id: '7', name: 'Potato', category: 'Vegetable', icon: '🥔' },
  { id: '22', name: 'Sweet Potato', category: 'Vegetable', icon: '🍠' },
  { id: '8', name: 'Sugarcane', category: 'Commercial', icon: '🎋' },
  { id: '9', name: 'Banana', category: 'Fruit', icon: '🍌' },
  { id: '10', name: 'Chili', category: 'Vegetable', icon: '🌶️' },
  { id: '23', name: 'Green Chili', category: 'Vegetable', icon: '🌶️' },
  { id: '24', name: 'Red Chili', category: 'Vegetable', icon: '🌶️' },
  { id: '11', name: 'Groundnut', category: 'Oilseed', icon: '🥜' },
  { id: '12', name: 'Corn', category: 'Grain', icon: '🌽' },
  { id: '13', name: 'Carrot', category: 'Vegetable', icon: '🥕' },
  { id: '14', name: 'Cabbage', category: 'Vegetable', icon: '🥬' },
  { id: '15', name: 'Cauliflower', category: 'Vegetable', icon: '🥦' },
  { id: '16', name: 'Brinjal', category: 'Vegetable', icon: '🍆' },
  { id: '25', name: 'Bottle Gourd', category: 'Vegetable', icon: '🥒' },
  { id: '26', name: 'Bitter Gourd', category: 'Vegetable', icon: '🥒' },
  { id: '28', name: 'Gourd', category: 'Vegetable', icon: '🥒' },
  { id: '17', name: 'Peas', category: 'Vegetable', icon: '🫛' },
  { id: '18', name: 'Soybean', category: 'Oilseed', icon: '🫘' },
  { id: '19', name: 'Pumpkin', category: 'Vegetable', icon: '🎃' },
  { id: '20', name: 'Garlic', category: 'Vegetable', icon: '🧄' },
  { id: '21', name: 'Ginger', category: 'Vegetable', icon: '🫚' },
];

export const INDIAN_STATES = [
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh', 'Goa', 'Gujarat',
  'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka', 'Kerala', 'Madhya Pradesh',
  'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Punjab',
  'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh',
  'Uttarakhand', 'West Bengal', 'Delhi'
];

export const TRANSLATIONS: Record<string, any> = {
  en: {
    welcome: 'Welcome to KisanSetu',
    i_am_a: 'I am a...',
    farmer: 'Farmer',
    buyer: 'Buyer',
    transporter: 'Transporter',
    admin: 'Admin',
    continue: 'Continue',
    login_phone: 'Login with Phone',
    enter_phone: 'Enter 10-digit mobile number',
    verify: 'Verify OTP',
    add_crop: 'Add New Crop',
    my_listings: 'My Crops',
    market_prices: 'Market Prices',
    negotiations: 'Negotiations',
    quantity: 'Quantity',
    expected_price: 'Expected Price',
    grade: 'Quality Grade',
    harvest_date: 'Harvest Date',
    submit: 'Submit Listing',
    low_stock: 'Low Stock',
    fair_price: 'Fair Price',
    high_price: 'High Price',
    below_market: 'Below Market',
    competitive: 'Competitive',
    slightly_above: 'Slightly Above',
    significantly_above: 'Significantly Above',
    price_advice_high: 'Hard to sell, consider lowering',
    price_advice_slightly_high: 'Negotiation likely',
    price_advice_competitive: 'Optimal price for selling',
    price_advice_low: 'Will sell very fast',
    home: 'Home',
    offers: 'Offers',
    earnings: 'Earnings',
    profile: 'Profile',
    total_earned: 'Total Earned',
    volume_sold: 'Volume Sold',
    pending: 'Pending',
    sales_breakdown: 'Sales Breakdown',
    sold_to: 'Sold to',
    search_crops: 'Search crops or location...',
    find_harvests: 'Find Fresh Harvests',
    negotiate: 'Negotiate',
    order_history: 'Order History',
    active_deliveries: 'Active Deliveries',
    earnings_balance: 'Earnings Balance',
    tips_for_success: 'Tips for Success',
    view_offers: 'View Offers',
    edit_profile: 'Edit Profile',
    publish_harvest: 'Publish Harvest',
    arrange_delivery: 'Arrange Delivery',
    mandi_avg: 'Mandi Average',
    current_offer: 'Current Offer',
    difference: 'Difference',
    edit: 'Edit',
    delete: 'Delete',
    govt_msp: 'Govt MSP',
    nearby_mandi: 'Nearby Mandi',
    arrange_pickup: 'Arrange Pickup',
    confirm_pickup: 'Confirm Pickup',
    enter_pickup_code: 'Enter Pickup OTP',
    pickup_success: 'Harvest picked up successfully!',
    your_price: 'Your Price',
    market_comparison: 'Market Comparison',
    benchmarking: 'Price Benchmarking',
    est_transport_cost: 'Est. Transport Cost',
    distance: 'Distance',
    total_bill: 'Total Bill',
    pay_on_delivery: 'Pay on Delivery',
    pickup_address: 'Pickup Address',
    expected_pickup_date: 'Expected Pickup Date',
    select_transporter: 'Select Transporter',
    vehicle_management: 'Vehicle Management',
    vehicle_type: 'Vehicle Type',
    capacity: 'Capacity (kg)',
    cost_per_km: 'Cost per km (₹)',
    license_plate: 'License Plate',
    save_vehicle: 'Save Vehicle Details',
    my_orders: 'My Orders',
    order_id: 'Order ID',
    transporter_info: 'Transporter Info',
  },
  hi: {
    welcome: 'किसानसेतु में स्वागत है',
    i_am_a: 'मैं एक हूँ...',
    farmer: 'किसान',
    buyer: 'खरीददार',
    transporter: 'परिवहनकर्ता',
    admin: 'व्यवस्थापक',
    continue: 'जारी रखें',
    login_phone: 'फोन से लॉगिन करें',
    enter_phone: '10 अंकों का मोबाइल नंबर दर्ज करें',
    verify: 'ओटीपी सत्यापित करें',
    add_crop: 'नई फसल जोड़ें',
    my_listings: 'मेरी फसलें',
    market_prices: 'बाजार भाव',
    negotiations: 'बातचीत',
    quantity: 'मात्रा',
    expected_price: 'अपेक्षित मूल्य',
    grade: 'गुणवत्ता ग्रेड',
    harvest_date: 'कटाई की तारीख',
    submit: 'लिस्टिंग जमा करें',
    below_market: 'बाजार से कम',
    competitive: 'प्रतिस्पर्धी',
    slightly_above: 'थोड़ा ऊपर',
    significantly_above: 'काफी ऊपर',
    price_advice_high: 'बेचना मुश्किल है, कम करने पर विचार करें',
    price_advice_slightly_high: 'बातचीत की संभावना',
    price_advice_competitive: 'बिक्री के लिए इष्टतम मूल्य',
    price_advice_low: 'बहुत तेजी से बिकेगा',
    home: 'होम',
    offers: 'ऑफर',
    earnings: 'कमाई',
    profile: 'प्रोफाइल',
    total_earned: 'कुल कमाई',
    volume_sold: 'कुल बिक्री',
    pending: 'लंबित',
    sales_breakdown: 'बिक्री का विवरण',
    sold_to: 'को बेचा',
    search_crops: 'फसल या स्थान खोजें...',
    find_harvests: 'ताजा फसलें खोजें',
    negotiate: 'बातचीत करें',
    order_history: 'ऑर्डर इतिहास',
    active_deliveries: 'सक्रिय डिलीवरी',
    earnings_balance: 'कमाई शेष',
    tips_for_success: 'सफलता के सुझाव',
    view_offers: 'ऑफर देखें',
    edit_profile: 'प्रोफाइल संपादित करें',
    publish_harvest: 'फसल प्रकाशित करें',
    arrange_delivery: 'डिलीवरी व्यवस्थित करें',
    mandi_avg: 'मंडी औसत',
    current_offer: 'वर्तमान ऑफर',
    difference: 'अंतर',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    govt_msp: 'सरकारी एमएसपी',
    nearby_mandi: 'पास की मंडी',
    arrange_pickup: 'पिकअप की व्यवस्था करें',
    confirm_pickup: 'पिकअप की पुष्टि करें',
    enter_pickup_code: 'पिकअप ओटीपी दर्ज करें',
    pickup_success: 'फसल सफलतापूर्वक उठा ली गई है!',
    your_price: 'आपका मूल्य',
    market_comparison: 'बाजार तुलना',
    benchmarking: 'मूल्य बेंचमार्किंग',
    est_transport_cost: 'अनुमानित परिवहन लागत',
    distance: 'दूरी',
    total_bill: 'कुल बिल',
    pay_on_delivery: 'डिलीवरी पर भुगतान',
    pickup_address: 'पिकअप का पता',
    expected_pickup_date: 'अपेक्षित पिकअप तिथि',
    select_transporter: 'परिवहनकर्ता चुनें',
    vehicle_management: 'वाहन प्रबंधन',
    vehicle_type: 'वाहन का प्रकार',
    capacity: 'क्षमता (किग्रा)',
    cost_per_km: 'लागत प्रति किमी (₹)',
    license_plate: 'लाइसेंस प्लेट',
    save_vehicle: 'वाहन विवरण सहेजें',
    my_orders: 'मेरे ऑर्डर',
    order_id: 'ऑर्डर आईडी',
    transporter_info: 'परिवहनकर्ता विवरण',
  },
  te: {
    welcome: 'కిసాన్‌సేతుకు స్వాగతం',
    i_am_a: 'నేను ఒక...',
    farmer: 'రైతు',
    buyer: 'కొనుగోలుదారు',
    transporter: 'రవాణాదారు',
    admin: 'అడ్మిన్',
    continue: 'కొనసాగించు',
    login_phone: 'ఫోన్‌తో లాగిన్ అవ్వండి',
    enter_phone: '10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి',
    verify: 'OTP ధృవీకరించండి',
    add_crop: 'కొత్త పంటను జోడించండి',
    my_listings: 'నా పంటలు',
    market_prices: 'మార్కెట్ ధరలు',
    negotiations: 'బేరసారాలు',
    quantity: 'పరిమాణం',
    expected_price: 'ఆశించిన ధర',
    grade: 'నాణ్యత గ్రేడ్',
    harvest_date: 'కోత తేదీ',
    submit: 'సమర్పించండి',
    below_market: 'మార్కెట్ కంటే తక్కువ',
    competitive: 'పోటీ ధర',
    slightly_above: 'కొంచెం ఎక్కువ',
    significantly_above: 'చాలా ఎక్కువ',
    price_advice_high: 'అమ్మడం కష్టం, తగ్గించండి',
    price_advice_slightly_high: 'బేరసారాల అవకాశం ఉంది',
    price_advice_competitive: 'అమ్మడానికి సరైన ధర',
    price_advice_low: 'చాలా వేగంగా అమ్ముడవుతుంది',
    home: 'హోమ్',
    offers: 'ఆఫర్లు',
    earnings: 'సంపాదన',
    profile: 'ప్రొఫైల్',
    total_earned: 'మొత్తం సంపాదన',
    volume_sold: 'అమ్మిన పరిమాణం',
    pending: 'పెండింగ్',
    sales_breakdown: 'విక్రయాల వివరాలు',
    sold_to: 'కి అమ్మబడింది',
    search_crops: 'పంటలు లేదా స్థలం కోసం వెతకండి...',
    find_harvests: 'తాజా పంటలను కనుగొనండి',
    negotiate: 'బేరం చేయండి',
    order_history: 'ఆర్డర్ చరిత్ర',
    active_deliveries: 'యాక్టివ్ డెలివరీలు',
    earnings_balance: 'సంపాదన నిల్వ',
    tips_for_success: 'విజయానికి చిట్కాలు',
    view_offers: 'ఆఫర్లను చూడండి',
    edit_profile: 'ప్రొఫైల్ సవరించండి',
    publish_harvest: 'పంటను ప్రచురించండి',
    arrange_delivery: 'డెలివరీ ఏర్పాటు చేయండి',
    mandi_avg: 'మండీ సగటు',
    current_offer: 'ప్రస్తుత ఆఫర్',
    difference: 'తేడా',
    edit: 'సవరించు',
    delete: 'తొలగించు',
    govt_msp: 'ప్రభుత్వ MSP',
    nearby_mandi: 'సమీప మండీ',
    arrange_pickup: 'పికప్ ఏర్పాటు చేయండి',
    confirm_pickup: 'పికప్ నిర్ధారించండి',
    enter_pickup_code: 'పికప్ OTP నమోదు చేయండి',
    pickup_success: 'పంట విజయవంతంగా పికప్ చేయబడింది!',
    your_price: 'మీ ధర',
    market_comparison: 'మార్కెట్ పోలిక',
    benchmarking: 'ధర బెంచ్ మార్కింగ్',
    est_transport_cost: 'అంచనా రవాణా ఖర్చు',
    distance: 'దూరం',
    total_bill: 'మొత్తం బిల్లు',
    pay_on_delivery: 'డెలివరీ సమయంలో చెల్లింపు',
    pickup_address: 'పికప్ చిరునామా',
    expected_pickup_date: 'పికప్ తేదీ',
    select_transporter: 'రవాణాదారుని ఎంచుకోండి',
    vehicle_management: 'వాహన నిర్వహణ',
    vehicle_type: 'వాహన రకం',
    capacity: 'సామర్థ్యం (kg)',
    cost_per_km: 'కిమీకి ఖర్చు (₹)',
    license_plate: 'లైసెన్స్ ప్లేట్',
    save_vehicle: 'వాహన వివరాలను సేవ్ చేయండి',
    my_orders: 'నా ఆర్డర్లు',
    order_id: 'ఆర్డర్ ID',
    transporter_info: 'రవాణాదారు సమాచారం',
  },
  ta: {
    welcome: 'கிசான் சேதுவுக்கு வரவேற்கிறோம்',
    i_am_a: 'நான் ஒரு...',
    farmer: 'விவசாயி',
    buyer: 'கொள்முதல் செய்பவர்',
    transporter: 'போக்குவரத்து செய்பவர்',
    admin: 'நிர்வாகி',
    continue: 'தொடரவும்',
    login_phone: 'தொலைபேசி மூலம் உள்நுழையவும்',
    enter_phone: '10 இலக்க மொபைல் எண்ணை உள்ளிடவும்',
    verify: 'OTP சரிபார்க்கவும்',
    add_crop: 'புதிய பயிரைச் சேர்க்கவும்',
    my_listings: 'எனது பயிர்கள்',
    market_prices: 'சந்தை விலைகள்',
    negotiations: 'பேச்சுவார்த்தை',
    quantity: 'அளவு',
    expected_price: 'எதிர்பார்க்கும் விலை',
    grade: 'தரம்',
    harvest_date: 'அறுவடை தேதி',
    submit: 'சமர்ப்பிக்கவும்',
    below_market: 'சந்தையை விட குறைவு',
    competitive: 'சரியான விலை',
    slightly_above: 'சற்று அதிகம்',
    significantly_above: 'மிகவும் அதிகம்',
    price_advice_high: 'விற்பது கடினம், குறைக்கலாம்',
    price_advice_slightly_high: 'பேரம் பேச வாய்ப்புள்ளது',
    price_advice_competitive: 'விற்பனைக்கு ஏற்ற விலை',
    price_advice_low: 'மிக வேகமாக விற்பனையாகும்',
    home: 'முகப்பு',
    offers: 'சலுகைகள்',
    earnings: 'வருமானம்',
    profile: 'சுயவிவரம்',
    total_earned: 'மொத்த வருமானம்',
    volume_sold: 'விற்பனை செய்யப்பட்ட அளவு',
    pending: 'நிலுவையில் உள்ளது',
    sales_breakdown: 'விற்பனை விவரம்',
    sold_to: 'விற்கப்பட்டது',
    search_crops: 'பயிர்கள் அல்லது இடத்தை தேடவும்...',
    find_harvests: 'புதிய அறுவடைகளைக் கண்டறியவும்',
    negotiate: 'பேச்சுவார்த்தை நடத்தவும்',
    order_history: 'ஆர்டர் வரலாறு',
    active_deliveries: 'செயலில் உள்ள விநியோகங்கள்',
    earnings_balance: 'வருமான இருப்பு',
    tips_for_success: 'வெற்றிக்கான குறிப்புகள்',
    view_offers: 'சலுகைகளைப் பார்க்கவும்',
    edit_profile: 'சுயவிவரத்தை மாற்றவும்',
    publish_harvest: 'அறுவடை வெளியிடவும்',
    arrange_delivery: 'விநியோகத்தை ஏற்பாடு செய்யவும்',
    mandi_avg: 'மண்டி சராசரி',
    current_offer: 'தற்போதைய சலுகை',
    difference: 'வித்தியாசம்',
    edit: 'தொகு',
    delete: 'நீக்கு',
    govt_msp: 'அரசு MSP',
    nearby_mandi: 'அருகிலுள்ள மண்டி',
    arrange_pickup: 'பிக்கப்பை ஏற்பாடு செய்யுங்கள்',
    confirm_pickup: 'பிக்கப்பை உறுதிப்படுத்தவும்',
    enter_pickup_code: 'பிக்கப் OTP ஐ உள்ளிடவும்',
    pickup_success: 'அறுவடை வெற்றிகரமாக பிக்கப் செய்யப்பட்டது!',
    your_price: 'உங்கள் விலை',
    market_comparison: 'சந்தை ஒப்பீடு',
    benchmarking: 'விலை ஒப்பீடு',
    est_transport_cost: 'மதிப்பிடப்பட்ட போக்குவரத்து செலவு',
    distance: 'தூரம்',
    total_bill: 'மொத்த பில்',
    pay_on_delivery: 'டெலிவரியில் பணம் செலுத்துதல்',
    pickup_address: 'பிக்கப் முகவரி',
    expected_pickup_date: 'பிக்கப் தேதி',
    select_transporter: 'போக்குவரத்தை தேர்ந்தெடுக்கவும்',
    vehicle_management: 'வாகன மேலாண்மை',
    vehicle_type: 'வாகன வகை',
    capacity: 'திறன் (கிலோ)',
    cost_per_km: 'கிமீக்கு செலவு (₹)',
    license_plate: 'உரிமத் தட்டு',
    save_vehicle: 'வாகன விவரங்களைச் சேமிக்கவும்',
    my_orders: 'எனது ஆர்டர்கள்',
    order_id: 'ஆர்டர் ஐடி',
    transporter_info: 'போக்குவரத்து தகவல்',
  },
  kn: {
    welcome: 'ಕಿಸಾನ್‌ಸೇತುಗೆ ಸ್ವಾಗತ',
    i_am_a: 'ನಾನು ಒಬ್ಬ...',
    farmer: 'ರೈತ',
    buyer: 'ಖರೀದಿದಾರ',
    transporter: 'ಸಾರಿಗೆದಾರ',
    admin: 'ಅಡ್ಮಿನ್',
    continue: 'ಮುಂದುವರಿಸಿ',
    login_phone: 'ಫೋನ್ ಮೂಲಕ ಲಾಗ್ ಇನ್ ಮಾಡಿ',
    enter_phone: '10 ಅಂಕಿಗಳ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
    verify: 'OTP ಪರಿಶೀಲಿಸಿ',
    add_crop: 'ಹೊಸ ಬೆಳೆಯನ್ನು ಸೇರಿಸಿ',
    my_listings: 'ನನ್ನ ಬೆಳೆಗಳು',
    market_prices: 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು',
    negotiations: 'ಚೌಕಾಸಿ',
    quantity: 'ಪ್ರಮಾಣ',
    expected_price: 'ನಿರೀಕ್ಷಿತ ಬೆಲೆ',
    grade: 'ಗುಣಮಟ್ಟದ ಗ್ರೇಡ್',
    harvest_date: 'ಕೊಯ್ಲು ದಿನಾಂಕ',
    submit: 'ಸಲ್ಲಿಸಿ',
    below_market: 'ಮಾರುಕಟ್ಟೆಗಿಂತ ಕಡಿಮೆ',
    competitive: 'ಸ್ಪರ್ಧಾತ್ಮಕ ಬೆಲೆ',
    slightly_above: 'ಸ್ವಲ್ಪ ಹೆಚ್ಚು',
    significantly_above: 'ಗಮನಾರ್ಹವಾಗಿ ಹೆಚ್ಚು',
    price_advice_high: 'ಮಾರಾಟ ಕಷ್ಟ, ಕಡಿಮೆ ಮಾಡಿ',
    price_advice_slightly_high: 'ಚೌಕಾಸಿಗೆ ಅವಕಾಶವಿದೆ',
    price_advice_competitive: 'ಮಾರಾಟಕ್ಕೆ ಸೂಕ್ತವಾದ ಬೆಲೆ',
    price_advice_low: 'ಬಹಳ ವೇಗವಾಗಿ ಮಾರಾಟವಾಗುತ್ತದೆ',
    home: 'ಮುಖಪುಟ',
    offers: 'ಆಫರ್ಗಳು',
    earnings: 'ಗಳಿಕೆ',
    profile: 'ಪ್ರೊಫೈಲ್',
    total_earned: 'ಒಟ್ಟು ಗಳಿಕೆ',
    volume_sold: 'ಮಾರಾಟವಾದ ಪ್ರಮಾಣ',
    pending: 'ಬಾಕಿ',
    sales_breakdown: 'ಮಾರಾಟದ ವಿವರ',
    sold_to: 'ಗೆ ಮಾರಾಟ ಮಾಡಲಾಗಿದೆ',
    search_crops: 'ಬೆಳೆಗಳು ಅಥವಾ ಸ್ಥಳವನ್ನು ಹುಡುಕಿ...',
    find_harvests: 'ತಾಜಾ ಕೊಯ್ಲುಗಳನ್ನು ಹುಡುಕಿ',
    negotiate: 'ಚೌಕಾಸಿ ಮಾಡಿ',
    order_history: 'ಆರ್ಡರ್ ಇತಿಹಾಸ',
    active_deliveries: 'ಸಕ್ರಿಯ ವಿತರಣೆಗಳು',
    earnings_balance: 'ಗಳಿಕೆ ಬಾಕಿ',
    tips_for_success: 'ಯಶಸ್ಸಿನ ಸಲಹೆಗಳು',
    view_offers: 'ಆಫರ್ ನೋಡಿ',
    edit_profile: 'ಪ್ರೊಫೈಲ್ ತಿದ್ದಿ',
    publish_harvest: 'ಬೆಳೆಯನ್ನು ಪ್ರಕಟಿಸಿ',
    arrange_delivery: 'ವಿತರಣೆ ವ್ಯವಸ್ಥೆ ಮಾಡಿ',
    mandi_avg: 'ಮಂಡಿ ಸರಾವರಿ',
    current_offer: 'ಪ್ರಸ್ತುತ ಆಫರ್',
    difference: 'ವ್ಯತ್ಯಾಸ',
    edit: 'ತಿದ್ದಿ',
    delete: 'ಅಳಿಸಿ',
    govt_msp: 'ಸರ್ಕಾರಿ MSP',
    nearby_mandi: 'ಹತ್ತಿರದ ಮಂಡಿ',
    arrange_pickup: 'ಪಿಕಪ್ ವ್ಯವಸ್ಥೆ ಮಾಡಿ',
    confirm_pickup: 'ಪಿಕಪ್ ಖಚಿತಪಡಿಸಿ',
    enter_pickup_code: 'ಪಿಕಪ್ OTP ನಮೂದಿಸಿ',
    pickup_success: 'ಬೆಳೆಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಪಿಕಪ್ ಮಾಡಲಾಗಿದೆ!',
    your_price: 'ನಿಮ್ಮ ಬೆಲೆ',
    market_comparison: 'ಮಾರುಕಟ್ಟೆ ಹೋಲಿಕೆ',
    benchmarking: 'ಬೆಲೆ ಹೋಲಿಕೆ',
    est_transport_cost: 'ಅಂದಾಜು ಸಾರಿಗೆ ವೆಚ್ಚ',
    distance: 'ದೂರ',
    total_bill: 'ಒಟ್ಟು ಬಿಲ್',
    pay_on_delivery: 'ವಿತರಣೆಯ ಸಮಯದಲ್ಲಿ ಪಾವತಿ',
    pickup_address: 'ಪಿಕಪ್ ವಿಳಾಸ',
    expected_pickup_date: 'ಪಿಕಪ್ ದಿನಾಂಕ',
    select_transporter: 'ಸಾರಿಗೆದಾರರನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
    vehicle_management: 'ವಾಹನ ನಿರ್ವಹಣೆ',
    vehicle_type: 'ವಾಹನ ಪ್ರಕಾರ',
    capacity: 'ಸಾಮರ್ಥ್ಯ (ಕೆಜಿ)',
    cost_per_km: 'ಕಿಮೀ ವೆಚ್ಚ (₹)',
    license_plate: 'ಲೈಸೆನ್ಸ್ ಪ್ಲೇಟ್',
    save_vehicle: 'ವಾಹನ ವಿವರಗಳನ್ನು ಉಳಿಸಿ',
    my_orders: 'ನನ್ನ ಆರ್ಡರ್‌ಗಳು',
    order_id: 'ಆರ್ಡರ್ ಐಡಿ',
    transporter_info: 'ಸಾರಿಗೆದಾರರ ಮಾಹಿತಿ',
  }
};
